variable "aws_region" {
  description = "AWS Region for the Control Plane account."
  type        = string
  default     = "ap-northeast-1"
}

variable "cognito_issuer_url" {
  description = "Exact Cognito User Pool issuer URL, including the user pool ID path."
  type        = string

  validation {
    condition     = can(regex("^https://[^/]+/.+", var.cognito_issuer_url))
    error_message = "cognito_issuer_url must be the HTTPS Cognito issuer URL including the user pool path."
  }
}

variable "api_lambda_zip_path" {
  description = "Path to the Hako API Lambda ZIP generated by make build-api-lambda."
  type        = string
  default     = "../../../../../build/hako-api.zip"
}

variable "github_webhook_secret_arn" {
  description = "Optional Secrets Manager ARN holding the GitHub App webhook secret; empty disables GitHub webhook ingress."
  type        = string
  default     = ""
}

variable "api_lambda_image_uri" {
  description = "Optional immutable same-Region ECR image URI for the blue/green API Lambda candidate. Empty keeps ZIP deployment active."
  type        = string
  default     = ""
}

variable "api_lambda_image_active" {
  description = "Route API Gateway to the prepared image Lambda candidate after it has been validated."
  type        = bool
  default     = false
}

variable "default_workspace_image" {
  description = "Image identifier passed to newly created Workspaces."
  type        = string
  default     = "hako-dev:latest"
}

variable "tags" {
  description = "Additional resource tags, such as a disposable E2E run ID. Hako ownership tags are reserved."
  type        = map(string)
  default     = {}
}

variable "enable_outbox_dispatcher" {
  description = "Explicitly enable the scheduled Outbox Dispatcher after Resource Plane queues and role policies are ready."
  type        = bool
  default     = false
}

variable "dispatcher_lambda_zip_path" {
  description = "Path to the Outbox Dispatcher arm64 Lambda ZIP generated by make build-dispatcher-lambda."
  type        = string
  default     = "../../../../../build/hako-dispatcher.zip"
}

variable "enable_github_webhook_processor" {
  description = "Opt in to the scheduled GitHub webhook Installation repository event processor."
  type        = bool
  default     = false
}

variable "github_webhook_processor_lambda_zip_path" {
  description = "Path to the webhook processor Lambda ZIP generated by make build-webhook-processor-lambda."
  type        = string
  default     = "../../../../../build/hako-webhook-processor.zip"
}

variable "resource_plane_manifest_json" {
  description = "Version 1 Resource Plane registration manifest JSON for the optional scheduled Dispatcher."
  type        = string
  default     = ""
}

variable "cognito_user_pool_id" {
  description = "ID of the Cognito User Pool used by the Control Plane."
  type        = string

  validation {
    condition     = can(regex("^[A-Za-z0-9-]+_[A-Za-z0-9]+$", var.cognito_user_pool_id))
    error_message = "cognito_user_pool_id must be a Cognito User Pool ID such as ap-northeast-1_Example123."
  }
}

variable "cognito_cli_callback_urls" {
  description = "OAuth callback URLs registered on the public Hako CLI app client."
  type        = list(string)
  default     = ["http://127.0.0.1:53682/callback"]
}
