CREATE TABLE IF NOT EXISTS workload_runs (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL REFERENCES tenants(id),
    kind TEXT NOT NULL CHECK (kind IN ('job', 'agent', 'preview')),
    requested_by TEXT REFERENCES users(id),
    github_installation_id BIGINT,
    github_repository_id BIGINT,
    commit_sha TEXT,
    ref TEXT NOT NULL DEFAULT '',
    runtime_class TEXT NOT NULL,
    trust_level TEXT NOT NULL CHECK (trust_level IN ('untrusted', 'trusted', 'privileged')),
    desired_state TEXT NOT NULL CHECK (desired_state IN ('running', 'cancelled')),
    state TEXT NOT NULL CHECK (state IN ('pending', 'queued', 'provisioning', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out')),
    resource_plane_id TEXT REFERENCES resource_planes(id),
    idempotency_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    timeout_seconds BIGINT NOT NULL CHECK (timeout_seconds BETWEEN 1 AND 86400),
    timeout_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_code TEXT,
    revision BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, idempotency_key),
    FOREIGN KEY (tenant_id, github_installation_id, github_repository_id)
        REFERENCES tenant_github_repositories(tenant_id, installation_id, github_repository_id),
    CHECK ((github_installation_id IS NULL AND github_repository_id IS NULL) OR (github_installation_id > 0 AND github_repository_id > 0)),
    CHECK (timeout_at > created_at)
)
